blank_issues_enabled: false
contact_links:
  - name: searchkannadamovies
    url: https://t.me/searchkannadamovies
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ultroid.tech/
    about: Basic documentation for setting up.
